import json
from google.cloud import firestore


class DAO(object):
    def __init__(self):
        self.db = firestore.Client()

    def add_item(self, item_property):
        item_ref = self.db.collection('collection')
        # the item id will be autogenerated if it is not specified (check the exam paper for specifics about this)
        item_ref.document().set({'item_property': item_property})

    def get_item(self, itemid):
        item = self.db.collection('collection').document(itemid).get()
        rv = item.to_dict() if item.exists else None
        return rv

    def update_item(self, itemid, new_property):
        item_ref = self.db.collection('collection').document(itemid)
        item_ref.update({'item_property': new_property})

    def delete_item(self, itemid):
        ref = self.db.collection('collection')
        item = ref.document(itemid).get()
        if item.exists:
            item.reference.delete()
        else:
            print('No such item exists!')

    def get_top_k_items(self, k=4):
        items = self.db.collection('collection').order_by('attribute', direction=firestore.Query.DESCENDING).limit(k).stream()
        rv = [item.to_dict() for item in items if item.exists]
        return rv

    def query_items(self, attribute, operator, value):
        # Possible "operator" values: '==', '!=', '>=', '<=', '>', '<'
        items = self.db.collection('collection').where(attribute, operator, value).stream()
        rv = [item.to_dict() for item in items if item.exists]
        return rv

    # def increase_attribute(self, itemid):
    #     # valid for numeric values
    #     self.db.collection('collection').document(itemid).update({"attribute": firestore.Increment(1)})

    def get_items_with_identifier(self):
        items = self.db.collection('collection').stream()
        rv = [
            {**item.to_dict(), 'id': item.id}
            for item in items if item.exists
        ]
        return rv

    def clean_db(self):
        items = self.db.collection('collection').list_documents()
        for i in items:
            i.delete()


if __name__ == '__main__':
    dao = DAO()
